In [4]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)
print(array_list)

['1' '2' '3' '4' '5']


In [ ]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
to print the data types of both the variables

In [5]:
type(list_)

list

In [7]:
type(array_list)

numpy.ndarray

In [ ]:
different between both:-
Well, the main difference between List and ArrayList is that List is an interface while ArrayList is a class. Most importantly, it implements the List interface, which also means that ArrayList is a subtype of the List interface

In [ ]:
2. Write a code to print the data type of each and every element of both the variables list_ and 
arra_list.

In [8]:
import numpy as np

list_ = [ '1' , '2' , '3' , '4' , '5' ]

array_list = np.array(object = list_)
print(array_list)

['1' '2' '3' '4' '5']


In [11]:
array_list.dtype

dtype('<U1')

In [12]:
type(list_)

list

In [ ]:
Q3. Considering the following changes in the variable, array_list:

In [13]:
array_list = np.array(object = list_, dtype = int)

In [14]:
print(array_list)

[1 2 3 4 5]


In [16]:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)
print(num_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape

(ii) size

In [17]:
num_array.size

6

In [19]:
num_array.shape

(2, 3)

In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
creation function.

In [30]:
import numpy as np
array=np.zeros(9).reshape((3,3))
print(array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [24]:
import numpy as np
array=np.identity(5)
print(array)#3x3 matrix

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
